import * as THREE from 'three';
import {World,createSky} from './world.js';
import {SaveSystem,Player,Vehicle,EnemyManager,MissionSystem,WantedSystem,Effects} from './systems.js';
import {WEAPONS,VEHICLES,MISSIONS,DISTRICTS,getMission,districtFor} from './content.js';
const $=id=>document.getElementById(id);
class Events{constructor(){this.m={}}on(k,f){(this.m[k]??=[]).push(f)}emit(k,...a){for(const f of this.m[k]||[])f(...a)}}
class Input{
 constructor(){this.keys={};this.lookX=0;this.lookY=0;this.pointer=false;this.lastX=0;this.lastY=0;window.addEventListener('keydown',e=>{this.keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('mousemove',e=>{if(this.pointer){this.lookX=e.movementX;this.lookY=e.movementY}});window.addEventListener('mousedown',e=>{if(e.button===0)this.keys.Mouse0=true;if(e.button===2)this.pointer=true});window.addEventListener('mouseup',e=>{if(e.button===0)this.keys.Mouse0=false});window.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('pointerlockchange',()=>{this.pointer=document.pointerLockElement===document.body});document.body.addEventListener('click',()=>{if(!this.pointer)document.body.requestPointerLock?.()},{once:false});window.addEventListener('touchstart',e=>{this.touch=e.touches[0]},{passive:true});window.addEventListener('touchmove',e=>{if(!this.touch)return;const t=e.touches[0];this.lookX=(t.clientX-this.touch.clientX)*.04;this.lookY=(t.clientY-this.touch.clientY)*.04;this.touch=t},{passive:true});}
 frame(){const k=this.keys;const out={forward:(k.KeyW?1:0)-(k.KeyS?1:0),strafe:(k.KeyD?1:0)-(k.KeyA?1:0),sprint:!!(k.ShiftLeft||k.ShiftRight),fire:!!(k.Mouse0||k.Space),reload:!!k.KeyR,brake:!!k.Space,exit:!!k.KeyF,lookX:this.lookX,lookY:this.lookY};this.lookX=0;this.lookY=0;return out}
}
class CrazyBridge{
 constructor(){this.ready=false;this.sdk=null;this.init()}
 async init(){try{if(window.CrazyGames?.SDK){this.sdk=window.CrazyGames.SDK;await this.sdk.init();this.ready=true;console.log('CrazyGames SDK ready')}}catch(e){console.warn('CrazyGames SDK unavailable',e)}}
 gameplayStart(){try{this.sdk?.game?.gameplayStart()}catch{}}
 gameplayStop(){try{this.sdk?.game?.gameplayStop()}catch{}}
 async ad(type,reward){if(!this.ready||!this.sdk?.ad)return false;return new Promise(resolve=>{this.sdk.ad.requestAd(type,{adStarted:()=>{window.game?.pause(true)},adFinished:()=>{window.game?.pause(false);reward?.();resolve(true)},adError:()=>{window.game?.pause(false);resolve(false)}})})}
}
class Game{
 constructor(){window.game=this;this.save=new SaveSystem();this.input=new Input();this.events=new Events();this.crazy=new CrazyBridge();this.paused=false;this.clock=new THREE.Clock();this.setupRenderer();this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x030514);this.scene.fog=new THREE.FogExp2(0x050612,.00165);this.camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.05,2600);this.camera.position.set(0,4,-8);this.world=new World(this.scene);createSky(this.scene);this.setupLights();this.effects=new Effects(this.scene);this.scene.userData.effects=this.effects;this.scene.userData.events=this.events;this.player=new Player(this.scene,this.world,this.save);this.enemies=new EnemyManager(this.scene,this.world,this.player);this.missions=new MissionSystem(this.scene,this.world,this.player,this.save,this.enemies);this.wanted=new WantedSystem(this.player);this.vehicles=[];this.spawnVehicles();this.bindEvents();this.setupUI();this.loading();}
 setupRenderer(){this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;document.getElementById('game').appendChild(this.renderer.domElement);addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)})}
 setupLights(){const hemi=new THREE.HemisphereLight(0x566cbb,0x080914,1.4);this.scene.add(hemi);const moon=new THREE.DirectionalLight(0x89a7ff,2.2);moon.position.set(-300,500,-200);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-700;moon.shadow.camera.right=700;moon.shadow.camera.top=700;moon.shadow.camera.bottom=-700;this.scene.add(moon)}
 spawnVehicles(){const spots=[['runner',30,30],['runner',-80,120],['viper',210,-140],['viper',-280,-220],['phantom',500,250],['titan',-500,340],['specter',760,-250],['runner',-700,700],['viper',700,700]];for(const [type,x,z] of spots)this.vehicles.push(new Vehicle(this.scene,this.world,type,x,z))}
 loading(){let p=0;const id=setInterval(()=>{p+=Math.random()*18+8;p=Math.min(100,p);$('load-progress').style.width=p+'%';$('load-text').textContent=p<35?'GENERATING DISTRICTS...':p<70?'SPAWNING TRAFFIC...':p<90?'LOADING CAMPAIGN...':'READY';if(p>=100){clearInterval(id);$('loading').classList.add('hidden');$('hud').classList.remove('hidden');this.crazy.gameplayStart();this.showToast('WELCOME TO NEON CITY');this.openMission(0);this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}},80)}
 bindEvents(){this.events.on('enemyKilled',e=>{this.missions.onKill();this.save.data.kills++;this.save.save();this.wanted.add(.25);this.effects.burst(e.group.position,0xff2bc2,12)});this.events.on('playerDead',()=>this.dead());this.events.on('missionStarted',m=>{this.showToast('MISSION: '+m.title)});this.events.on('missionComplete',m=>{this.showToast(`MISSION COMPLETE +$${m.reward.toLocaleString()}`);this.crazy.ad('midgame')});this.events.on('enterCar',c=>this.showToast(c.spec.name+' // F TO EXIT'));this.events.on('vehicleDestroyed',c=>this.effects.explosion(c.group.position));$('resume').onclick=()=>this.closeMenu();$('missions').onclick=()=>this.openMissions();$('garage').onclick=()=>this.openGarage();$('settings').onclick=()=>this.showToast('WASD MOVE • SHIFT SPRINT • MOUSE AIM • LMB FIRE • R RELOAD • F ENTER/EXIT');$('retry').onclick=()=>{this.hide('death-screen');this.player.health=100;this.player.armor=25;this.player.group.position.copy(this.world.getSpawn());this.enemies.clear();this.paused=false};$('death-menu').onclick=()=>{this.hide('death-screen');this.openMenu()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>this.hide(b.dataset.close));}
 setupUI(){this.renderMissions();this.renderGarage()}
 renderMissions(){const root=$('mission-list');root.innerHTML='';MISSIONS.forEach((m,i)=>{const locked=!this.missions.canStart(m);const d=document.createElement('div');d.className='mission-card '+(locked?'locked':'');d.innerHTML=`<h3>${String(i+1).padStart(2,'0')} — ${m.title}</h3><p>${m.brief}</p><p>District: ${districtFor(...(m.district==='dock'?[-520,-420]:[0,0])).name} · Reward <span class="reward">$${m.reward.toLocaleString()}</span></p><button ${locked?'disabled':''}>${locked?'LOCKED':'START MISSION'}</button>`;d.querySelector('button').onclick=()=>{this.hide('mission-screen');this.startMission(m.id)};root.appendChild(d)})}
 renderGarage(){const root=$('garage-list');root.innerHTML='';Object.entries(VEHICLES).forEach(([id,v])=>{const owned=this.save.data.vehicles.includes(id),d=document.createElement('div');d.className='car-card '+(!owned?'locked':'');d.innerHTML=`<h3>${v.name}</h3><p>TOP SPEED ${Math.round(v.topSpeed*3.2)} KM/H · ARMOR ${v.health}</p><p>${owned?'Owned':'$'+v.price.toLocaleString()}</p><button>${owned?(this.save.data.vehicle===id?'SELECTED':'SELECT'):'BUY'}</button>`;d.querySelector('button').onclick=()=>{if(owned){this.save.data.vehicle=id;this.save.save();this.showToast(v.name+' SELECTED');this.renderGarage()}else if(this.save.data.cash>=v.price){this.save.data.cash-=v.price;this.save.data.vehicles.push(id);this.save.data.vehicle=id;this.save.save();this.showToast('PURCHASED '+v.name);this.renderGarage()}else this.showToast('NOT ENOUGH CASH')};root.appendChild(d)})}
 openMission(i){const m=MISSIONS[Math.min(i,MISSIONS.length-1)];if(this.missions.canStart(m))this.startMission(m.id)}
 startMission(id){if(!this.missions.start(id)){this.showToast('MISSION LOCKED');return}this.updateHUD()}
 openMissions(){this.renderMissions();this.show('mission-screen');this.paused=true}
 openGarage(){this.renderGarage();this.show('garage-screen');this.paused=true}
 openMenu(){this.show('menu');this.paused=true;this.crazy.gameplayStop()}
 closeMenu(){this.hide('menu');this.paused=false;this.crazy.gameplayStart()}
 show(id){$(id).classList.remove('hidden')};hide(id){$(id).classList.add('hidden')}
 pause(v){this.paused=v}
 dead(){this.paused=true;$('death-text').textContent=`You finished with $${this.save.data.cash.toLocaleString()} in the bank.`;this.show('death-screen');this.crazy.gameplayStop()}
 showToast(t){const e=$('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.classList.add('hidden'),2400)}
 updateHUD(){const p=this.player,m=this.missions.active;$('cash').textContent='$'+this.save.data.cash.toLocaleString();$('hp').style.width=Math.max(0,p.health)+'%';$('armor').style.width=Math.max(0,p.armor)+'%';const stars=Math.ceil(this.wanted.stars);$('wanted').innerHTML='WANTED <b>'+['☆','☆','☆','☆','☆'].map((s,i)=>i<stars?'★':s).join(' ')+'</b>';$('ammo').textContent=`${p.ammo} / ${p.reserve}`;$('weapon-name').textContent=p.weapon().name;if(m){$('objective').textContent=m.brief;$('mission-progress').style.width=Math.min(100,(m.type==='combat'||m.type==='boss'?this.missions.kills/m.kills:this.missions.distance/m.distance)*100)+'%'}else $('objective').textContent='Free roam — explore Neon City'}
 findNearbyCar(){let best=null,bd=5;for(const c of this.vehicles){const d=c.group.position.distanceTo(this.player.group.position);if(d<bd&&!c.occupied){best=c;bd=d}}return best}
 interaction(){if(this.player.inCar)return;if(this.input.keys.KeyF){this.input.keys.KeyF=false;const c=this.findNearbyCar();if(c)this.player.enterCar(c)}}
 update(dt){if(this.paused)return;const input=this.input.frame();this.interaction();this.player.update(dt,input,this.camera);this.enemies.update(dt);this.missions.update(dt);this.wanted.update(dt,this.enemies.enemies);this.effects.update(dt);this.world.update(performance.now()/1000);this.updateHUD();this.drawMap();if(this.player.inCar)$('speed').textContent=Math.round(Math.abs(this.player.car.velocity)*3.2)+' KM/H';else $('speed').textContent='ON FOOT'}
 drawMap(){const c=$('map'),ctx=c.getContext('2d');ctx.clearRect(0,0,180,180);ctx.fillStyle='#05050d';ctx.fillRect(0,0,180,180);const p=this.player.inCar?this.player.car.group.position:this.player.group.position;ctx.save();ctx.translate(90,90);ctx.scale(.08,.08);ctx.translate(-p.x,-p.z);ctx.strokeStyle='#303747';ctx.lineWidth=34;for(let x=-1000;x<=1000;x+=160){ctx.beginPath();ctx.moveTo(x,-1100);ctx.lineTo(x,1100);ctx.stroke()}for(let z=-1000;z<=1000;z+=160){ctx.beginPath();ctx.moveTo(-1100,z);ctx.lineTo(1100,z);ctx.stroke()}ctx.fillStyle='#ff2bc2';for(const e of this.enemies.enemies){ctx.fillRect(e.group.position.x-8,e.group.position.z-8,16,16)}ctx.restore()}
 loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.update(dt);this.renderer.render(this.scene,this.camera);requestAnimationFrame(x=>this.loop(x))}
}
new Game();