import * as THREE from 'three';
import {VEHICLES} from './content.js';
const MOBILE=!!window.__NEON_MOBILE__;
function box(c,w,h,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08}));m.castShadow=false;return m}
export class TrafficCar{constructor(scene,world,road){this.scene=scene;this.world=world;this.group=new THREE.Group();this.group.position.set(road.x,.5,road.z);scene.add(this.group);const c=Object.values(VEHICLES)[Math.floor(Math.random()*Object.keys(VEHICLES).length)].color;this.group.add(box(c,1.7,.55,3.3));const roof=box(0x555b63,1.35,.55,1.55);roof.position.y=.6;this.group.add(roof);this.heading=road.angle;this.speed=7+Math.random()*10;this.life=0}update(dt){this.life+=dt;this.group.position.x+=Math.sin(this.heading)*this.speed*dt;this.group.position.z+=Math.cos(this.heading)*this.speed*dt;this.group.rotation.y=this.heading;if(Math.abs(this.group.position.x)>1250||Math.abs(this.group.position.z)>1250)this.life=99}}
export class TrafficSystem{constructor(scene,world){this.scene=scene;this.world=world;this.cars=[];this.timer=0}update(dt,player){this.timer-=dt;if(this.timer<=0&&this.cars.length<(MOBILE?4:14)){this.timer=MOBILE?2.5:1.1;const roads=this.world.roads;if(roads.length){const r=roads[Math.floor(Math.random()*roads.length)];this.cars.push(new TrafficCar(this.scene,this.world,r))}}for(const c of this.cars)c.update(dt);this.cars=this.cars.filter(c=>{if(c.life>90){c.group.removeFromParent();return false}return true})}}
export class PedestrianSystem{constructor(scene,world){this.scene=scene;this.world=world;this.people=[];this.timer=0}spawn(){const p=new THREE.Group();p.position.set((Math.random()-.5)*1200,.0,(Math.random()-.5)*1200);const b=box(Math.random()<.5?0x3d6fd8:0xe07b48,.35,1.25,.35);b.position.y=.63;p.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.18,MOBILE?6:8,MOBILE?4:6),new THREE.MeshStandardMaterial({color:0xc58f75}));h.position.y=1.45;p.add(h);this.scene.add(p);this.people.push({group:p,v:new THREE.Vector3((Math.random()-.5)*1.5,0,(Math.random()-.5)*1.5),life:30+Math.random()*90})}update(dt){this.timer-=dt;if(this.timer<0&&this.people.length<(MOBILE?5:20)){this.timer=MOBILE?4:1.8;this.spawn()}for(const p of this.people){p.life-=dt;p.group.position.addScaledVector(p.v,dt);p.group.rotation.y=Math.atan2(p.v.x,p.v.z)}for(let i=this.people.length-1;i>=0;i--)if(this.people[i].life<=0){this.people[i].group.removeFromParent();this.people.splice(i,1)}}}
export class PickupSystem{constructor(scene,save,events){this.scene=scene;this.save=save;this.events=events;this.items=[];this.timer=0}spawn(){const g=new THREE.Group();g.position.set((Math.random()-.5)*1200,.8,(Math.random()-.5)*1200);const m=new THREE.Mesh(new THREE.OctahedronGeometry(.6),new THREE.MeshStandardMaterial({color:0x48b96d,roughness:.3,metalness:.3}));g.add(m);this.scene.add(g);this.items.push({g,life:60+Math.random()*100})}update(dt,player){this.timer-=dt;if(this.timer<0&&this.items.length<(MOBILE?4:10)){this.timer=MOBILE?12:7;this.spawn()}for(let i=this.items.length-1;i>=0;i--){const x=this.items[i];x.life-=dt;x.g.rotation.y+=dt*2;x.g.position.y=.8+Math.sin(performance.now()/300+i)*.15;if(x.g.position.distanceTo(player.group.position)<2){const value=250+Math.floor(Math.random()*1750);this.save.addCash(value);this.events.emit('pickup',value);x.g.removeFromParent();this.items.splice(i,1);continue}if(x.life<=0){x.g.removeFromParent();this.items.splice(i,1)}}}}
export class WeatherSystem{constructor(scene){this.scene=scene;this.time=0;this.rain=null}update(dt){this.time+=dt}}
