import * as THREE from 'three';
import {DISTRICTS} from './content.js';
const UP=new THREE.Vector3(0,1,0);
const mat=(c,r=.65,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
export class World{
 constructor(scene){this.scene=scene;this.root=new THREE.Group();scene.add(this.root);this.colliders=[];this.buildings=[];this.lamps=[];this.roads=[];this.seed=71237;this.generate();}
 rnd(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296}
 noise(x,z){const n=Math.sin(x*12.9898+z*78.233)*43758.5453;return n-Math.floor(n)}
 generate(){this.makeGround();this.makeRoadGrid();this.makeBuildings();this.makeStreetFurniture();this.makeWater();this.makeHighway();this.makeDistrictLandmarks()}
 box(w,h,d,c,x,y,z,rough=.75,metal=.1){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,rough,metal));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;this.root.add(m);return m}
 makeGround(){const g=new THREE.PlaneGeometry(2600,2600,24,24);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,(this.noise(x*.012,z*.012)-.5)*1.6)}g.computeVertexNormals();const mesh=new THREE.Mesh(g,mat(0x070a12,.98,0));mesh.receiveShadow=true;this.root.add(mesh)}
 makeRoadGrid(){const road=mat(0x0b0d14,.92,.12),line=mat(0xd4d1a4,.7,0);for(let x=-1000;x<=1000;x+=160){const r=new THREE.Mesh(new THREE.BoxGeometry(34,.12,2200),road);r.position.set(x,.04,0);r.receiveShadow=true;this.root.add(r);for(let z=-1000;z<=1000;z+=80){const l=new THREE.Mesh(new THREE.BoxGeometry(1.5,.14,18),line);l.position.set(x,.12,z);this.root.add(l)}}for(let z=-1000;z<=1000;z+=160){const r=new THREE.Mesh(new THREE.BoxGeometry(2200,.12,34),road);r.position.set(0,.04,z);r.receiveShadow=true;this.root.add(r);for(let x=-1000;x<=1000;x+=80){const l=new THREE.Mesh(new THREE.BoxGeometry(18,.14,1.5),line);l.position.set(x,.12,z);this.root.add(l)}}}
 makeBuildings(){for(let x=-920;x<=920;x+=80)for(let z=-920;z<=920;z+=80){if(Math.abs(x%160)<1||Math.abs(z%160)<1||this.rnd()<.12)continue;const d=this.closestDistrict(x,z),h=10+Math.pow(this.rnd(),.58)*95,w=43+this.rnd()*22,dep=43+this.rnd()*22;const c=new THREE.Color(d.color).multiplyScalar(.06+this.rnd()*.09).getHex();const b=this.box(w,h,dep,c,x,h/2,z,.8,.28);this.buildings.push(b);this.colliders.push(new THREE.Box3().setFromObject(b));if(h>65)this.addRoof(b,h,d.color);if(this.rnd()<.35)this.addFacadeLights(b,w,h,dep,d.color)}}
 closestDistrict(x,z){let best=DISTRICTS[0],bd=Infinity;for(const d of DISTRICTS){const dx=x-d.center[0],dz=z-d.center[2],q=dx*dx+dz*dz;if(q<bd){bd=q;best=d}}return best}
 addFacadeLights(b,w,h,d,color){const glow=mat(color,.25,.35);const count=Math.min(14,Math.max(2,Math.floor(h/12)));for(let i=0;i<count;i++){const side=this.rnd()<.5?1:-1;const m=new THREE.Mesh(new THREE.BoxGeometry(2.8,1.4,.08),glow);m.position.set(b.position.x+(this.rnd()-.5)*(w-5),3+this.rnd()*(h-6),b.position.z+side*(d/2+.05));this.root.add(m)}}
 addRoof(b,h,color){const pole=this.box(.7,9,.7,0x202838,b.position.x,b.position.y+h/2+4.5,b.position.z,.5,.7);const light=new THREE.PointLight(color,1.3,38);light.position.copy(pole.position);this.root.add(light);this.lamps.push(light)}
 makeStreetFurniture(){for(let x=-960;x<=960;x+=160)for(let z=-960;z<=960;z+=160){for(const [dx,dz] of [[-14,-14],[14,14]]){if(this.rnd()<.7){const h=6.5;this.box(.3,h,.3,0x303646,x+dx,h/2,z+dz,.5,.65);const light=new THREE.PointLight(this.rnd()<.5?0x00eaff:0xff2bc2,1.1,20);light.position.set(x+dx,h,z+dz);this.root.add(light);this.lamps.push(light)}}}}
 makeWater(){const g=new THREE.PlaneGeometry(500,400);g.rotateX(-Math.PI/2);const w=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x031d2a,roughness:.12,metalness:.65,transparent:true,opacity:.92}));w.position.set(-720,-.15,-760);this.root.add(w)}
 makeHighway(){const pts=[[-1100,8,650],[-700,10,500],[-250,12,610],[250,14,520],[700,16,650],[1100,18,520]].map(v=>new THREE.Vector3(...v));const curve=new THREE.CatmullRomCurve3(pts);const samples=curve.getPoints(50);const roadMat=mat(0x151821,.82,.25);for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1],mid=a.clone().add(b).multiplyScalar(.5),len=a.distanceTo(b),ang=Math.atan2(b.x-a.x,b.z-a.z);const slab=new THREE.Mesh(new THREE.BoxGeometry(32,.6,len),roadMat);slab.position.copy(mid);slab.rotation.y=ang;this.root.add(slab);this.roads.push({x:mid.x,z:mid.z,angle:ang})}}
 makeDistrictLandmarks(){for(const d of DISTRICTS){const [x,,z]=d.center,h=18+d.level*7;const tower=this.box(9,h,9,d.color,x,h/2,z,.35,.75);const ring=new THREE.Mesh(new THREE.TorusGeometry(16+d.level*2,.55,8,32),new THREE.MeshBasicMaterial({color:d.color}));ring.position.set(x,h*.72,z);ring.rotation.x=Math.PI/2;this.root.add(ring);const l=new THREE.PointLight(d.color,2.2,110);l.position.set(x,h*.8,z);this.root.add(l);tower.userData.landmark=d.id)}}
 getSpawn(){return new THREE.Vector3(0,1.2,0)}
 isBlocked(pos,r=1){const p=new THREE.Vector3(pos.x,Math.max(1,pos.y),pos.z);for(const b of this.colliders){const q=b.clone().expandByScalar(r);if(q.containsPoint(p))return true}return false}
 districtAt(pos){return this.closestDistrict(pos.x,pos.z)}
 update(t){for(let i=0;i<this.lamps.length;i++)this.lamps[i].intensity=1.05+Math.sin(t*2+i*.7)*.25}
}
export function createSky(scene){const sky=new THREE.Mesh(new THREE.SphereGeometry(1800,24,12),new THREE.MeshBasicMaterial({color:0x030514,side:THREE.BackSide}));scene.add(sky);const arr=[];for(let i=0;i<700;i++)arr.push((Math.random()-.5)*2600,350+Math.random()*900,(Math.random()-.5)*2600);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0x8ea8ff,size:.8,sizeAttenuation:true})));return sky}
