import * as THREE from 'three';
import {DISTRICTS} from './content.js';
const UP=new THREE.Vector3(0,1,0);
const mat=(c,r=0.65,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
export class World{
 constructor(scene){this.scene=scene;this.root=new THREE.Group();scene.add(this.root);this.colliders=[];this.buildings=[];this.lamps=[];this.roads=[];this.seed=71237;this.generate();}
 rnd(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296}
 noise(x,z){let n=Math.sin(x*12.9898+z*78.233)*43758.5453;return n-Math.floor(n)}
 generate(){this.makeGround();this.makeRoadGrid();this.makeDistrictLandmarks();this.makeBuildings();this.makeStreetFurniture();this.makeWater();this.makeHighway();}
 makeGround(){const g=new THREE.PlaneGeometry(2600,2600,80,80);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,(this.noise(x*.012,z*.012)-.5)*2.2)}g.computeVertexNormals();const mesh=new THREE.Mesh(g,mat(0x070a12,.95,0));mesh.receiveShadow=true;this.root.add(mesh);}
 box(w,h,d,c,x,y,z,rough=.75,metal=.1){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,rough,metal));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;this.root.add(m);return m}
 makeRoadGrid(){const roadMat=mat(0x10121b,.92,.15),lineMat=mat(0x3a3d48,.8,.05);for(let x=-1000;x<=1000;x+=160){this.box(34,.12,2200,0x0b0d14,x,.04,0,.9,.05);for(let z=-1000;z<=1000;z+=48)this.box(2,.14,22,0xd4d1a4,x,.12,z,.7,0)}for(let z=-1000;z<=1000;z+=160){this.box(2200,.12,34,0x0b0d14,0,.04,z,.9,.05);for(let x=-1000;x<=1000;x+=48)this.box(22,.14,2,0xd4d1a4,x,.12,z,.7,0)}for(let x=-920;x<=920;x+=80)for(let z=-920;z<=920;z+=80){if(x%160===0||z%160===0)continue;const h=1.5+this.rnd()*4;this.box(7,.15,7,0x191c27,x,.13,z,.8,0)}}
 makeBuildings(){for(let x=-980;x<=980;x+=80){for(let z=-980;z<=980;z+=80){if(Math.abs(x%160)<1||Math.abs(z%160)<1)continue;const r=this.rnd();if(r<.08)continue;const w=42+this.rnd()*28,d=42+this.rnd()*28,h=10+Math.pow(this.rnd(),.55)*110;const dist=this.closestDistrict(x,z);const base=dist.color;const color=new THREE.Color(base).multiplyScalar(.08+this.rnd()*.08);const b=this.box(w,h,d,color.getHex(),x,h/2,z,.78,.3);this.buildings.push(b);this.colliders.push(new THREE.Box3().setFromObject(b));this.addWindows(b,w,h,d);if(h>75)this.addRoof(b,w,d)}}}
 closestDistrict(x,z){let best=DISTRICTS[0],bd=1e20;for(const d of DISTRICTS){const dx=x-d.center[0],dz=z-d.center[2],q=dx*dx+dz*dz;if(q<bd){bd=q;best=d}}return best}
 addWindows(b,w,h,d){const c=new THREE.Color().setHSL(this.rnd(),.75,.5);const wm=mat(c.getHex(),.25,.5);const rows=Math.max(1,Math.floor(h/7)),colsX=Math.max(1,Math.floor(w/7)),colsZ=Math.max(1,Math.floor(d/7));for(let y=5;y<h-3;y+=Math.max(7,h/rows)){for(let i=0;i<colsX;i++){if(this.rnd()<.22)continue;const win=new THREE.Mesh(new THREE.PlaneGeometry(3.1,2.2),wm);win.position.set(b.position.x-w/2+4+i*6.5,y,b.position.z+d/2+.02);this.root.add(win);const win2=win.clone();win2.position.z=b.position.z-d/2-.02;win2.rotation.y=Math.PI;this.root.add(win2)}for(let i=0;i<colsZ;i++){if(this.rnd()<.2)continue;const win=new THREE.Mesh(new THREE.PlaneGeometry(3.1,2.2),wm);win.position.set(b.position.x+w/2+.02,y,b.position.z-d/2+4+i*6.5);win.rotation.y=Math.PI/2;this.root.add(win)}}}
 addRoof(b,w,d){const antenna=this.box(1.2,12,1.2,0x202838,b.position.x,b.position.y+b.geometry.parameters.height/2+6,b.position.z,.5,.7);const lamp=new THREE.PointLight(0xff2bc2,1.4,45);lamp.position.copy(antenna.position);this.root.add(lamp)}
 makeStreetFurniture(){for(let x=-960;x<=960;x+=80)for(let z=-960;z<=960;z+=80){if(Math.abs(x%160)<1||Math.abs(z%160)<1)continue;if(this.rnd()<.48){const h=7;this.box(.45,h,.45,0x303646,x,h/2,z,.5,.7);const light=new THREE.PointLight(this.rnd()<.5?0x00eaff:0xff2bc2,1.5,24);light.position.set(x,h,z);this.root.add(light);this.lamps.push(light)}}}
 makeWater(){const geo=new THREE.PlaneGeometry(500,400,20,20);geo.rotateX(-Math.PI/2);const m=new THREE.MeshStandardMaterial({color:0x031d2a,roughness:.12,metalness:.65,transparent:true,opacity:.92});const water=new THREE.Mesh(geo,m);water.position.set(-720,-.15,-760);this.root.add(water)}
 makeHighway(){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-1100,8,650),new THREE.Vector3(-700,10,500),new THREE.Vector3(-250,12,610),new THREE.Vector3(250,14,520),new THREE.Vector3(700,16,650),new THREE.Vector3(1100,18,520)]);const pts=curve.getPoints(80);const geo=new THREE.BufferGeometry().setFromPoints(pts);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x454b5a}));this.root.add(line);for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],mid=a.clone().add(b).multiplyScalar(.5),len=a.distanceTo(b);this.box(32,.6,len,0x151821,mid.x,mid.y,mid.z,.8,.25);const ang=Math.atan2(b.x-a.x,b.z-a.z);this.roads.push({x:mid.x,z:mid.z,angle:ang})}}
 makeDistrictLandmarks(){for(const d of DISTRICTS){const [x,,z]=d.center;const h=20+d.level*8;const tower=this.box(10,h,10,d.color,x,h/2,z,.3,.8);const ring=new THREE.Mesh(new THREE.TorusGeometry(18+d.level*2,.6,8,48),new THREE.MeshBasicMaterial({color:d.color}));ring.position.set(x,h*.7,z);ring.rotation.x=Math.PI/2;this.root.add(ring);const light=new THREE.PointLight(d.color,3,130);light.position.set(x,h*.8,z);this.root.add(light)}}
 getSpawn(){return new THREE.Vector3(0,1.2,0)}
 isBlocked(pos,r=1){const p=new THREE.Vector3(pos.x,pos.y,pos.z);for(const b of this.colliders){const q=b.clone().expandByScalar(r);if(q.containsPoint(p))return true}return false}
 districtAt(pos){let best=DISTRICTS[0],bd=Infinity;for(const d of DISTRICTS){const dx=pos.x-d.center[0],dz=pos.z-d.center[2],v=dx*dx+dz*dz;if(v<bd){bd=v;best=d}}return best}
 update(t){for(const b of this.buildings){if(b.position.y<3)continue}for(let i=0;i<this.lamps.length;i++){const l=this.lamps[i];l.intensity=1.15+Math.sin(t*2+i)*.35}}
}
export function createSky(scene){const sky=new THREE.Mesh(new THREE.SphereGeometry(1800,32,16),new THREE.MeshBasicMaterial({color:0x030514,side:THREE.BackSide}));scene.add(sky);const stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0x8ea8ff,size:.8,sizeAttenuation:true}));const arr=[];for(let i=0;i<1200;i++){arr.push((Math.random()-.5)*2600,350+Math.random()*900,(Math.random()-.5)*2600)}stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));scene.add(stars);return sky}
